blank_issues_enabled: false
contact_links:
  - name: uBingo discussions (aka. forum)
    url: https://github.com/Unately/uBingo/discussions
    about: Please ask and answer questions here.
  - name: Discord 
    url: https://discord.gg/BeYVQ3fhF4
    about: â— This is a German Discord
    about: Only German! ğŸº
