
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 572984
	#The name of the modpack
	modpackName = "uBingo"
	#The version of the modpack
	modpackVersion = "v1.3"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

