#Align player to camera on left & right clicks (delayed by Flick Timeout)
aimPlayerOnInteract = true
#Delay in ticks between moments when player can flick towards the target in third person
#Range: 1 ~ 20
flickTimeout = 7
#Angle in degrees within the player will slightly follow camera rotation
#Range: 0 ~ 90
followYaw = 45

