name: "ğŸ› ï¸ Issue"

on:
  # The issues event below is only needed for the default (auto) mode,
  # you can remove it otherwise
  issues:
    types: [ assigned ]
  # The issue_comment event below is only needed for the ChatOps mode,
  # you can remove it otherwise
  issue_comment:
    types: [ created ]
  pull_request:
    types: [ closed ]

jobs:
  create_issue_branch_job:
    runs-on: self-hosted
    name: "ğŸš— Create Issue Branch"
    steps:
      - name: "ğŸšŒ Create Branch"
        uses: robvanderleek/create-issue-branch@v1.5
        branchName: 'issue/${issue.number}-hah'
        autoCloseIssue: true
        openPR: true
        copyIssueDescriptionToPR: true
        copyIssueAssigneeToPR: true
        copyIssueProjectsToPR: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}